name: seq2seq

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Download testdata
        run: |
          make datasetdl

      - name: Seq2Seq(Attention)
        run: |
          go run cmd/seq2seq_attn/main.go --dir ./testdata
