name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Download testdata
        run: |
          make testdatadl

      - name: Tests
        run: |
          make test

      - name: MNIST
        run: |
          make mnist1

      - name: CBOW
        run: |
          make cbow

      - name: RNNLM(Elman)
        run: |
          make rnnlm10

      - name: RNNLM(LSTM)
        run: |
          make lstm10

      - name: RNNLMGen(LSTM)
        run: |
          make rnnlmgen0

      - name: Seq2Seq
        run: |
          make seq2seq

      - name: Codecov
        uses: codecov/codecov-action@v3
