name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Tests
        run: |
          make mnistdl
          make test

      - name: MNIST
        run: |
          make mnistdl
          make mnist1

      - name: Codecov
        uses: codecov/codecov-action@v3
