name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Download testdata
        run: |
          make datasetdl

      - name: Tests
        run: |
          make test

      - name: MNIST
        run: |
          make mnist1

      - name: CBOW(Simple)
        run: |
          make cbow_simple

      - name: CBOW(Negative Sampling)
        run: |
          make cbow

      - name: RNNLM(Simple)
        run: |
          make rnnlm

      - name: RNNLM(LSTM)
        run: |
          make rnnlm_lstm

      - name: RNNLMGen(LSTM)
        run: |
          make rnnlm_gen

      - name: Seq2Seq
        run: |
          make seq2seq

      - name: Seq2Seq(Attention)
        run: |
          make seq2seq_attn

      - name: Codecov
        uses: codecov/codecov-action@v3
